# Generated by Django 6.0.4 on 2026-04-19 03:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
